### ISSUE TITLE
for swf's sprite

### ISSUE THREAD

**Issue by skream27** [maltaisn/swf-convert#4]
can we do the same for swf's sprite, maltaisn? i don't have any code information, I don't even know how to run it. can you help?

**Comment by maltaisn** [comment]
I'm not sure I understand. If you have a `.swf` file you can convert it to pdf or svg. Follow the instructions in the readme for how to run it.

**Comment by skream27** [comment]
the program you made converts the frame of the swf, but I need the one for the sprite of the swf. i'll send you a file, will you examine it? please open with jpexs flash decompiler and click sprites, you'll understand what I mean.
[file-b.zip](https://github.com/maltaisn/swf-convert/files/7196601/file-b.zip)

**Comment by maltaisn** [comment]
Ok I made a change and it seems to work. The tool was made to parse only top-level frames and a single frame in sprites. Other frames in sprites were discarded since this is typically used for animation, not static content. I added an option to create pages for all frames in a sprite.

However there's another issue: your file indicates the frame dimensions to be 20x20 twips (1x1 pixel), so there's virtually nothing getting displayed. Are you aware of where the actual dimensions are set? If not, I can always provide an extra option to override the frame dimensions.

**Comment by skream27** [comment]
Maltaisn, thank you very much for all the hard work and effort you put into this project. I would like to opt for the option to change the dimensions manually. Can you send?

**Comment by maltaisn** [comment]
[Here's a pre-release](https://github.com/maltaisn/swf-convert/files/7206885/swf-convert.zip) with two new options:
- `-DrecursiveFrames`: parse frames recursively in sprites
- `-DframeSize=[w,h]`: manual frame size override (in inches)

I think I get the correct output with:
```
java -jar swf-convert.jar pdf file-b.swf -DrecursiveFrames -DframeSize=[8.5,11]
```
I guessed for the dimensions but it looks right. You tell me if it works for other files if you have any.
